services:
  - type: web
    name: face-recognition-biometric
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn app:app -c gunicorn.conf.py --preload
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /
    healthCheckTimeout: 300
    autoDeploy: true 