services:
  - type: web
    name: face-recognition-biometric
    env: python
    buildCommand: |
      pip install -r requirements.txt
      echo "Downloading only GhostFaceNet model..."
      python download_models.py
      mkdir -p ~/.deepface
      mkdir -p model_cache
      if [ -d "/opt/render/.deepface" ]; then
        cp -R /opt/render/.deepface/* ~/.deepface/
        echo "Copied model files from /opt/render/.deepface to ~/.deepface"
      fi
    startCommand: gunicorn app:app --timeout 240 --workers 1 --config gunicorn.conf.py
    plan: standard
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: FLASK_ENV
        value: production
      - key: DEEPFACE_HOME
        value: /opt/render/project/model_cache
      - key: MODEL_NAME
        value: GhostFaceNet
      - key: TF_FORCE_GPU_ALLOW_GROWTH
        value: "true"
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "3"
      - key: CUDA_VISIBLE_DEVICES
        value: "-1"  # Force CPU only
      - key: TF_KERAS_BACKEND
        value: "tensorflow"
    healthCheckPath: / 