services:
  - type: web
    name: face-recognition-biometric
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 1
    plan: standard
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.22
      - key: FLASK_ENV
        value: production
    healthCheckPath: / 